#!/bin/bash

cmd=$@

# TODO: No cmd passed?

pyenv_versions=$(pyenv versions --bare)

for pyenv_version in ${pyenv_versions[*]}; do
    pyenv_version=$(pyenv root)/versions/$pyenv_version/bin/python
    new_cmd=${cmd//python/$pyenv_version}
    echo $new_cmd
done
