#!/bin/bash

cmd=$@

# TODO: No cmd passed?

pyenv_versions=$(pyenv versions --bare)
#pyenv local $pyenv_versions

for pyenv_version in ${pyenv_versions[*]}; do
    #pyenv_version="$(echo $pyenv_version | cut -c-3)"
    pyenv_version=$(pyenv root)/versions/$pyenv_version/bin/python
    new_cmd=${cmd//python/$pyenv_version}
    echo $new_cmd
done
